### ISSUE TITLE
Is running logspout-logstash and ELK stack run on different docker host supported?

### ISSUE THREAD

**Issue by kennethwork99** [amouat/logspout-logstash#1]
Is there a reason why logspout-logstash and ELK stack cannot run on different docker host?
Using the following 2 docker-compose files work fine if both runs on same docker host.
My goal is to set up ELK stack on the network as a service and any (docker or none-docker) client can submit logs remotely to ELK. First I am trying to get docker clients to work first.

Since ELK runs on VM host 172.16.33.44, I  was hoping that I can simply change from 
command: logstash://logstash:5000
to 
logstash://172.16.33.44:5000
Note on ELK we expose logstach port 5000 to the local host.
1. docker-compose_logspout.yml
```

version: "3"

services:
    pytest_selenium_hub:
        image: selenium/hub:3.4.0
        container_name: pytest_selenium_hub
        ports:
            - "4444:4444"
        environment:
            - TZ=America/Los_Angeles
        networks:
            - selenium_grid_internal

    chromenode:
        image: "selenium/node-chrome-debug:3.4.0"
        depends_on:
            - pytest_selenium_hub
        ports:
            - 5900
        environment:
            - TZ=America/Los_Angeles
            - no_proxy=localhost
            - HUB_PORT_4444_TCP_ADDR=pytest_selenium_hub
            - HUB_PORT_4444_TCP_PORT=4444
        networks:
            - selenium_grid_internal

    logspout:
        image: amouat/logspout-logstash
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock
        ports:
            - "8000:80"
        ### - Does not work if go directly to 172.16.33.44
        command: logstash://172.16.33.44:5000
        ### Works fine using following if client containers and elk stack on same docker host
        #command: logstash://logstash:5000
        networks:
            - selenium_grid_internal

networks:
    selenium_grid_internal:

```

2. docker-compose_elk.yml
```

version: "3"

services:

    myhello:
        image: myhello:0.0.1
        depends_on:
            - logspout
        networks:
            - selenium_grid_internal

    logspout:
        image: amouat/logspout-logstash
        depends_on:
            - logstash
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock
        ports:
            - "8000:80"
        command: logstash://logstash:5000
        networks:
            - selenium_grid_internal

    logstash:
        image: logstash:2.0
        depends_on:
            - elasticsearch
        volumes:
            - ./logstash.conf:/etc/logstash.conf
        environment:
            LOGSPOUT: ignore
        links:
            - elasticsearch
        ports:
            #- "5000:5000/udp"
            - "5000:5000"
        command: -f /etc/logstash.conf
        networks:
            - selenium_grid_internal

    elasticsearch:
        image: elasticsearch:5.4.3
        environment:
            LOGSPOUT: ignore
        ports:
            - "9200:9200"
            - "9300:9300"
        networks:
            - selenium_grid_internal

    kibana:
        image: kibana:5.4.3
        depends_on:
            - elasticsearch
        environment:
            LOGSPOUT: ignore
            ELASTICSEARCH_URL: http://elasticsearch:9200
        links:
            - elasticsearch
        ports:
            - "5601:5601"
        networks:
            - selenium_grid_internal

networks:
    selenium_grid_internal:

```

3. logstash.conf

```

input {
  tcp {
    port => 5000
    codec => json
  }
  udp {
    port => 5000
    codec => json
  }
}

output {
    elasticsearch { hosts => "elasticsearch" }
    stdout { codec => rubydebug }
}

```
